# Generated by Django 3.2.2 on 2021-05-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='title')),
                ('content', models.TextField(blank=True, max_length=128, verbose_name='content')),
                ('createdTime', models.DateTimeField(verbose_name='createdTime')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'article',
            },
        ),
    ]
