# Generated by Django 3.2.2 on 2021-05-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_user_articles_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
